feat(backend): Init model relationship
awesome-academy/bts_awesome_01 pull request #4
Opened 2019-03-27 13:40 UTC by SonNguyenTrong

## About
Thêm quan hệ cho các bảng 
Loại bỏ những bảng trung gian không cần thiết
## Note

## UI changes

2019-03-27 13:40 UTC, SonNguyenTrong commented
ready

2019-03-28 06:48 UTC, tranvanmy requested changes

2019-03-28 06:48 UTC, tranvanmy commented on app/Models/UserBooking.php
> +    protected $table = 'user_bookings';
Bỏ đi , cái này ko cần thiết

2019-03-28 06:48 UTC, tranvanmy commented on app/Models/UserFavorite.php
> +    protected $table = 'user_favorites';
cái này cũng vậy

2019-03-28 06:48 UTC, tranvanmy commented on app/Models/UserRate.php
> +    protected $table = 'user_rates';
Bỏ đi

2019-03-28 06:48 UTC, tranvanmy commented
commented

2019-03-29 11:09 UTC, SonNguyenTrong commented
ready

2019-03-29 11:10 UTC, tranvanmy approved these changes

2019-03-29 11:10 UTC, merged